# Spring Datasource
spring:
  datasource:
#    url: jdbc:hsqldb:file:/Users/topopelon/Desktop/db/db;hsqldb.lock_file=false
    url: jdbc:hsqldb:mem:.
    username: sa
    password:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
  jpa:
#    hibernate:
#      ddl-auto: create
    open-in-view: false